language: node_js
node_js:
  - "4.0.0"

branches:
  only:
    - master

before_install:
  - npm install bower -g
  - npm install karma -g
  - npm install karma-cli -g

script:
  - npm install
  - karma start

cache:
  directories:
  - bower_components
  - node_modules

notifications:
  email:
    - darren@octono.com
