// Code generated by Microsoft (R) AutoRest Code Generator 0.9.7.0
// Changes may cause incorrect behavior and will be lost if the code is regenerated.

using System;
using System.Collections.Generic;
using System.Linq;
using Newtonsoft.Json.Linq;
using NgQuestion.WebApi.Tests.Models;

namespace NgQuestion.WebApi.Tests.Models
{
    public static partial class BoardCollection
    {
        /// <summary>
        /// Deserialize the object
        /// </summary>
        public static IList<Board> DeserializeJson(JToken inputObject)
        {
            IList<Board> deserializedObject = new List<Board>();
            foreach (JToken iListValue in ((JArray)inputObject))
            {
                Board board = new Board();
                board.DeserializeJson(iListValue);
                deserializedObject.Add(board);
            }
            return deserializedObject;
        }
    }
}
